### ISSUE TITLE
OPUS files render incorrect playtime

### ISSUE THREAD

**Issue by cblanken** [ubuntu-flutter-community/musicpod#1090] opened 2024-12-12 14:28 UTC
I've noticed that my local .opus files when imported, display the incorrect playtime. Usually in the hours for a file that only has a playtime of a few minutes.

For example, here's an image of an .mp3 file displaying the correct playtime and two .opus files displaying 31+ and 42+ hours when there playtimes are closer to 3 or 4 minutes.
![image](https://github.com/user-attachments/assets/b1f01f0a-4507-43f1-806a-da21a0679c9c)

EDIT: this is with version 2.5.0

**Comment by ClementBeal** [comment] 2024-12-12 14:48
Hi!

I think this one is for me. `musicpod` is using my library : https://github.com/ClementBeal/audio_metadata_reader/issues

Could you please provide open an issue to this repo and give of the opus that doesn't work? I'll fix it as soon as possible

**Comment by cblanken** [comment] 2024-12-13 14:02
> Could you please open an issue to this repo and give the opus that doesn't work? I'll fix it as soon as possible

Sure thing :+1:

**Comment by ClementBeal** [comment] 2024-12-14 11:41
Hi!

The problem is `musicpoc 2.5.0` uses the version `0.0.9` of `audio_metadata_reader` and this version had a bug with the Opus duration.

If we use the latest version of `audio_metadata_reader`, the problem is solved. I'll try to create a PR.

**Comment by Feichtmeier** [comment] 2024-12-14 11:48
> Hi!
> 
> The problem is `musicpoc 2.5.0` uses the version `0.0.9` of `audio_metadata_reader` and this version had a bug with the Opus duration.
> 
> If we use the latest version of `audio_metadata_reader`, the problem is solved. The dev version of musicpod is up to date. We have to wait for a new release

Ohhh sorry I should have checked
Yes I just this in main already 
So this will be fixed with next major release, or if you use Ubuntu snap 🫰 it's in the edge channel already

**Closed** 2024-12-14 12:02 UTC
