### ISSUE TITLE
Window Size and Position

### ISSUE THREAD

**Issue by Crocodile73** [ubuntu-flutter-community/musicpod#823] opened 2024-08-03 11:27 UTC
Windows Version.

Good improvement if musicpod could remember the size and position of its window. Having to always resize on starting app, not great.

**Comment by Feichtmeier** [comment] 2024-08-04 16:01
hi :)
this is a duplicate of https://github.com/ubuntu-flutter-community/musicpod/issues/626
I close this in favour of the other one, thanks for creating issues

**Closed by Feichtmeier** 2024-08-04 16:01 UTC
