### ISSUE TITLE
Bug: No rounded corners on Ubuntu KDE 24.04

### ISSUE THREAD

**Issue by rolandixor** [ubuntu-flutter-community/musicpod#775] opened 2024-05-31 17:47 UTC
Of course, this is a low priority request, but seeing as most Gnome apps now have rounded corners, as do many of the KDE apps I use as well, Musicpod feels out of place. Simply rounding the corners of the app would resolve this.

![Screenshot_20240531_134711](https://github.com/ubuntu-flutter-community/musicpod/assets/558147/8d1eab89-47c7-4136-988d-3cc93e8322ac)

**Comment by Feichtmeier** [comment] 2024-05-31 18:24
> Of course, this is a low priority request, but seeing as most Gnome apps now have rounded corners, as do many of the KDE apps I use as well, Musicpod feels out of place. Simply rounding the corners of the app would resolve this.
> 
> ![Screenshot_20240531_134711](https://private-user-images.githubusercontent.com/558147/335683750-8d1eab89-47c7-4136-988d-3cc93e8322ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODAxMzYsIm5iZiI6MTcxNzE3OTgzNiwicGF0aCI6Ii81NTgxNDcvMzM1NjgzNzUwLThkMWVhYjg5LTQ3YzctNDEzNi05ODhkLTNjYzkzZTgzMjJhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxODIzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTI1ZjAzZjM2MzAwNDA0NmM0OWM2NDIwOGQwODQyZjQ2N2NmMGU3ZjgzZDliOGZkNGQwOGU3MTYyZmZhMjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kugB0rSo5VxSWcqgM4_jOo4gVx_CEZznjKMpqCJ09vQ)

HI! This is def a bug
musicpod has wonderful 4 rounded corners on ubuntu / macos / windows

could you share more about your system?

**Comment by rolandixor** [comment] 2024-05-31 18:26
Hi, I'm running Ubuntu 24.04, though I'm on KDE Plasma at the moment due to issues with on my system Gnome.

**Comment by Feichtmeier** [comment] 2024-05-31 18:36
@soumyaDghosh since you use kde at the moment could you have a look what could be the cause here?

**Comment by soumyaDghosh** [comment] 2024-05-31 20:30
I am currently on KDE Neon and just installed musicpod, and everything is fine here. 

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/72045785/d0702991-6391-4591-93f5-b83df23faad3)

Also, I can see some erros in the terminal. Can you share those? I guess this is something specific to your installation?

**Comment by Feichtmeier** [comment] 2024-05-31 20:58
wow this panel looks awesome, and thanks for checking

**Comment by rolandixor** [comment] 2024-06-01 03:00
Here are the errors I'm getting. I'm going to check and see if maybe it could be a theming issue as well.

```
Theme parsing error: gtk.css:1:21: Failed to import: Error opening file /home/rolandixor/snap/musicpod/1271/.config/gtk-3.0/colors.css: No such file or directory
package:media_kit_libs_linux registered.
media_kit: VideoOutput: video_output_new: 3179483827280
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 3179483827280, id: 3179302758032, rect: {left: 0, top: 0, width: 1, height: 1}}
flutter: NativeVideoController: Texture ID: 3179302758032
```

**Comment by rolandixor** [comment] 2024-06-01 03:06
Definitely something to do with the theme selected in KDE's settings. However, I noticed that even using the default Adwaita doesn't work (and that definitely should have rounded corners). Setting the theme to Yaru somehow resolves the issue.

**Comment by soumyaDghosh** [comment] 2024-06-01 12:24
> Definitely something to do with the theme selected in KDE's settings. However, I noticed that even using the default Adwaita doesn't work (and that definitely should have rounded corners). Setting the theme to Yaru somehow resolves the issue.

I am using KDE's default breeze theme.

**Comment by rolandixor** [comment] 2024-06-01 13:14
I should clarify: by KDE's settings, I mean its settings for GTK+ apps.

![Screenshot_20240601_091412](https://github.com/ubuntu-flutter-community/musicpod/assets/558147/0eede214-115d-4d85-b4fd-acaa4c7ca76a)

**Comment by rolandixor** [comment] 2024-08-21 03:57
This bug seems to have been fixed since, as I'm no longer able to replicate it.

**Comment by JaneSmith** [comment] 2024-09-13 12:59
I have this issue using the latest Flatpak from Flathub. No rounded corners.

**Comment by Feichtmeier** [comment] 2024-09-13 13:24
> I have this issue using the latest Flatpak from Flathub. No rounded corners.
> 
> I'm running Fedora Silverblue as my OS, but that shouldn't matter for Flatpak apps.

sorry to hear this. as this app has started and grown on ubuntu I did not really test it anywhere else but @TheShadowOfHassen and @dongfengweixiao did
Could you guys look into this please?

**Comment by TheShadowOfHassen** [comment] 2024-09-13 13:54
Downloading silverblue...

**Comment by TheShadowOfHassen** [comment] 2024-09-13 14:26
Yeah, I can replicate:

![image](https://github.com/user-attachments/assets/c14c5611-93bc-4a32-b13f-3c7c4a517fa0)

**Comment by TheShadowOfHassen** [comment] 2024-09-13 20:06
It's on debian too...

**Comment by TheShadowOfHassen** [comment] 2024-09-13 20:14
Ran musicpod from source on debian, it gives this error consistently across all versions, so it could be that.


![image](https://github.com/user-attachments/assets/c5e743d1-535b-46d5-8f50-fe599beb1f70)

**Comment by Feichtmeier** [comment] 2024-09-13 21:15
libhandy is missing I think

snap is working (as always :( )

**Comment by TheShadowOfHassen** [comment] 2024-09-13 22:58
> libhandy is missing I think
> 
> snap is working (as always :( )

That's a good idea, but I installed libhandy-dev on the debian system and still no rounded corners.

![image](https://github.com/user-attachments/assets/f8701865-83e0-413b-a24b-ce62bc674de4)

(what I installed via apt)

![image](https://github.com/user-attachments/assets/1fe5d7b6-bff4-46d0-ab40-007cd7fcdb61)

**Comment by TheShadowOfHassen** [comment] 2024-09-13 23:11
This is the snap version of musicpod. It has square corners. So I don't think its that.

![image](https://github.com/user-attachments/assets/25239b4e-03d6-4eb0-8281-0be370ec64b7)

**Comment by Feichtmeier** [comment] 2024-09-14 07:59
> This is the snap version of musicpod. It has square corners. So I don't think its that.
> 
> ![image](https://github.com/user-attachments/assets/25239b4e-03d6-4eb0-8281-0be370ec64b7)
> 

Oo what the hell
Why is it working on Ubuntu then?

**Comment by Feichtmeier** [comment] 2024-09-14 09:15
@TheShadowOfHassen while on fedora could you check canonical snaps made with flutter? snap-store for example?

**Comment by TheShadowOfHassen** [comment] 2024-09-14 12:46
This is the snaps store on debian. Rounded corners I think

![image](https://github.com/user-attachments/assets/5362fe6d-ee79-4b6f-8fb1-f0c445457266)

Can't get it to run on silverblue because I can't get that to work. Ubuntu doesn't support it, I guess.

**Comment by Feichtmeier** [comment] 2024-09-14 18:22
@JaneSmith updated the snap/flatpak please have a look if the bug is gone for you

**Comment by JaneSmith** [comment] 2024-09-15 01:20
It looks like it's fixed now after updating to the latest Flatpak version. Thanks!

**Closed** 2024-09-15 06:59 UTC
Labels: bug :bug:, flatpak
