### ISSUE TITLE
Issue with character encoding 

### ISSUE THREAD

**Issue by alculete** [ubuntu-flutter-community/musicpod#141] opened 2023-08-12 13:52 UTC
Special characters not showing very well.
The text in the search bar is in Portuguese.

![image](https://github.com/ubuntu-flutter-community/musicpod/assets/2129497/a13a01a4-7f6a-4445-8ddc-65f523f6480b)

**Comment by Feichtmeier** [comment] 2023-08-12 14:18
oh :thinking: that's not nice
does this input work in the flutter version of snap-store?

**Comment by alculete** [comment] 2023-08-12 14:30
The issue is not on what I write is on the result. Try to write Moçambique on the search bar. you will do the result.

**Comment by Feichtmeier** [comment] 2023-08-12 15:41
> Moçambique

oh ok
well the problem is in the radio browser lib I use
this is what I get in debug for your search term

![grafik](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/c08f587b-a459-497d-a884-ad8bcf58aa2a)

I see if I can band aid fix it otherwise we would need to open an issue on https://github.com/tomassasovsky/radio-browser-api.dart

**Comment by Feichtmeier** [comment] 2023-11-29 15:36
Hey @alculete  :)
I found the fix for this inside the radiobrowser api lib I am using
Made a PR there, until it is merged I use my fork here as a dep
Moçambique
![Bildschirmfoto 2023-11-29 um 16 36 06](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/93b2f519-8f01-4e9b-b06c-1ff5196504bc)
![Bildschirmfoto 2023-11-29 um 16 36 33](https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/4f8330cd-bcee-4df6-b81d-c8c3b512c6e3)

**Closed** 2023-11-29 15:41 UTC
